# This workflow uses a conditional to build release artifacts
# https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
# https://github.com/softprops/action-gh-release?tab=readme-ov-file#%EF%B8%8F-uploading-release-assets
name: Go Artifacts on Tagged Release
on:
  push:
    branches: [ "main" ]

jobs:
  test:
    uses: dtrejod/goexif/.github/workflows/go.yml@main
    if: startsWith(github.ref, 'refs/tags/')

  release:
    runs-on: ubuntu-latest
    needs:
      - test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Build Darwin amd64
      run: OS=darwin GOARCH=amd64 go build -v ./...  -o bin/goexif-amd64-darwin

    - name: Build Darwin arm64
      run: OS=darwin GOARCH=arm64 go build -v ./...  -o bin/goexif-arm64-darwin

    - name: Build Linux amd64
      run: OS=linux GOARCH=amd64 go build -v ./...  -o bin/goexif-amd64-linux

    - name: Build Linux arm64
      run: OS=linux GOARCH=arm64 go build -v ./...  -o bin/goexif-arm64-linux

    - name: Build Windows amd64
      run: OS=windows GOARCH=amd64 go build -v ./...  -o bin/goexif-amd64-windows.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/goexif-amd64-darwin
          bin/goexif-arm64-darwin
          bin/goexif-amd64-linux
          bin/goexif-arm64-linux
          bin/goexif-amd64-windows.exe
